import { LoteValidade, Produto, Usuario, Venda } from '../../../types';

export const USUARIOS_INICIAIS: Usuario[] = [
  {
    id: 'usr_admin_01',
    nome: 'Carlos Oliveira (Gerente)',
    login: 'admin',
    senhaHash: 'admin123',
    papel: 'ADMINISTRADOR',
    ativo: true,
    criadoEm: '2026-01-01T08:00:00Z',
  },
  {
    id: 'usr_caixa_01',
    nome: 'Mariana Silva (Caixa 01)',
    login: 'caixa',
    senhaHash: 'caixa123',
    papel: 'OPERADOR_CAIXA',
    ativo: true,
    criadoEm: '2026-01-10T08:00:00Z',
  },
  {
    id: 'usr_caixa_02',
    nome: 'João Santos (Caixa 02)',
    login: 'joao',
    senhaHash: '123456',
    papel: 'OPERADOR_CAIXA',
    ativo: true,
    criadoEm: '2026-02-01T08:00:00Z',
  },
];

export const PRODUTOS_INICIAIS: Produto[] = [
  {
    id: 'prod_001',
    codigoInterno: '101',
    nome: 'Arroz Tipo 1 Camil 5kg',
    descricao: 'Arroz branco longo e fino pacote de 5kg',
    categoria: 'Mercearia',
    precoCusto: 22.5,
    precoVenda: 29.9,
    quantidadeEstoque: 48,
    estoqueMinimo: 15,
    unidadeMedida: 'PCT',
    ativo: true,
    atualizadoEm: new Date().toISOString(),
  },
  {
    id: 'prod_002',
    codigoInterno: '102',
    nome: 'Feijão Carioca Kicaldo 1kg',
    descricao: 'Feijão carioca selecionado 1kg',
    categoria: 'Mercearia',
    precoCusto: 6.2,
    precoVenda: 8.9,
    quantidadeEstoque: 35,
    estoqueMinimo: 10,
    unidadeMedida: 'PCT',
    ativo: true,
    atualizadoEm: new Date().toISOString(),
  },
  {
    id: 'prod_003',
    codigoInterno: '103',
    nome: 'Óleo de Soja Liza 900ml',
    descricao: 'Óleo de soja refinado 900ml pet',
    categoria: 'Mercearia',
    precoCusto: 5.8,
    precoVenda: 7.5,
    quantidadeEstoque: 24,
    estoqueMinimo: 12,
    unidadeMedida: 'UN',
    ativo: true,
    atualizadoEm: new Date().toISOString(),
  },
  {
    id: 'prod_004',
    codigoInterno: '104',
    nome: 'Café Torrado Pilão Tradicional 500g',
    descricao: 'Café em pó tradicional vácuo 500g',
    categoria: 'Matinais',
    precoCusto: 14.0,
    precoVenda: 18.9,
    quantidadeEstoque: 40,
    estoqueMinimo: 10,
    unidadeMedida: 'PCT',
    ativo: true,
    atualizadoEm: new Date().toISOString(),
  },
  {
    id: 'prod_005',
    codigoInterno: '105',
    nome: 'Leite Integral Piracanjuba 1L',
    descricao: 'Leite longa vida integral tetra pak 1L',
    categoria: 'Laticínios',
    precoCusto: 3.8,
    precoVenda: 5.2,
    quantidadeEstoque: 6, // Estoque abaixo do mínimo (15) para disparar alerta!
    estoqueMinimo: 15,
    unidadeMedida: 'UN',
    ativo: true,
    atualizadoEm: new Date().toISOString(),
  },
  {
    id: 'prod_006',
    codigoInterno: '106',
    nome: 'Açúcar Refinado União 1kg',
    descricao: 'Açúcar refinado especial pacote 1kg',
    categoria: 'Mercearia',
    precoCusto: 3.4,
    precoVenda: 4.8,
    quantidadeEstoque: 50,
    estoqueMinimo: 10,
    unidadeMedida: 'PCT',
    ativo: true,
    atualizadoEm: new Date().toISOString(),
  },
  {
    id: 'prod_007',
    codigoInterno: '107',
    nome: 'Iogurte Morango Danone 170g',
    descricao: 'Iogurte natural sabor morango copo',
    categoria: 'Laticínios',
    precoCusto: 2.1,
    precoVenda: 3.5,
    quantidadeEstoque: 18,
    estoqueMinimo: 8,
    unidadeMedida: 'UN',
    ativo: true,
    atualizadoEm: new Date().toISOString(),
  },
  {
    id: 'prod_008',
    codigoInterno: '108',
    nome: 'Refrigerante Coca-Cola 2L',
    descricao: 'Refrigerante sabor cola pet 2 litros',
    categoria: 'Bebidas',
    precoCusto: 7.5,
    precoVenda: 10.5,
    quantidadeEstoque: 30,
    estoqueMinimo: 10,
    unidadeMedida: 'UN',
    ativo: true,
    atualizadoEm: new Date().toISOString(),
  },
  {
    id: 'prod_009',
    codigoInterno: '109',
    nome: 'Pão de Forma Tradicional Wickbold 500g',
    descricao: 'Pão de forma fatiado tradicional',
    categoria: 'Padaria',
    precoCusto: 5.0,
    precoVenda: 7.9,
    quantidadeEstoque: 14,
    estoqueMinimo: 5,
    unidadeMedida: 'PCT',
    ativo: true,
    atualizadoEm: new Date().toISOString(),
  },
  {
    id: 'prod_010',
    codigoInterno: '110',
    nome: 'Detergente Líquido Ypê Neutro 500ml',
    descricao: 'Detergente lava-louças neutro',
    categoria: 'Limpeza',
    precoCusto: 1.8,
    precoVenda: 2.8,
    quantidadeEstoque: 4, // Estoque baixo!
    estoqueMinimo: 12,
    unidadeMedida: 'UN',
    ativo: true,
    atualizadoEm: new Date().toISOString(),
  },
];

// Gerar datas relativas para demonstrar o controle de validade e alertas
const hoje = new Date();
const calcularDataRelativa = (dias: number): string => {
  const d = new Date(hoje);
  d.setDate(d.getDate() + dias);
  return d.toISOString().split('T')[0];
};

export const LOTES_INICIAIS: LoteValidade[] = [
  {
    id: 'lote_001',
    produtoId: 'prod_007', // Iogurte
    produtoNome: 'Iogurte Morango Danone 170g',
    numeroLote: 'LT-2026-DAN-01',
    dataFabricacao: calcularDataRelativa(-20),
    dataValidade: calcularDataRelativa(3), // Vence em 3 dias! Alerta CRÍTICO
    quantidade: 8,
    dataEntrada: calcularDataRelativa(-15),
  },
  {
    id: 'lote_002',
    produtoId: 'prod_009', // Pão de Forma
    produtoNome: 'Pão de Forma Tradicional Wickbold 500g',
    numeroLote: 'LT-2026-WB-88',
    dataFabricacao: calcularDataRelativa(-7),
    dataValidade: calcularDataRelativa(5), // Vence em 5 dias! Alerta CRÍTICO
    quantidade: 14,
    dataEntrada: calcularDataRelativa(-5),
  },
  {
    id: 'lote_003',
    produtoId: 'prod_005', // Leite
    produtoNome: 'Leite Integral Piracanjuba 1L',
    numeroLote: 'LT-2026-PIRA-12',
    dataFabricacao: calcularDataRelativa(-60),
    dataValidade: calcularDataRelativa(18), // Vence em 18 dias! Alerta ATENÇÃO
    quantidade: 6,
    dataEntrada: calcularDataRelativa(-40),
  },
  {
    id: 'lote_004',
    produtoId: 'prod_001', // Arroz
    produtoNome: 'Arroz Tipo 1 Camil 5kg',
    numeroLote: 'LT-2026-CAM-901',
    dataFabricacao: calcularDataRelativa(-30),
    dataValidade: calcularDataRelativa(180), // Validade distante (OK)
    quantidade: 48,
    dataEntrada: calcularDataRelativa(-20),
  },
];

export const VENDAS_INICIAIS: Venda[] = [
  {
    id: 'venda_antiga_001',
    numeroCupom: 1001,
    dataHora: new Date(Date.now() - 3600 * 1000 * 4).toISOString(),
    operadorId: 'usr_caixa_01',
    operadorNome: 'Mariana Silva',
    itens: [
      {
        id: 'iv_01',
        produtoId: 'prod_001',
        codigoInterno: '101',
        nomeProduto: 'Arroz Tipo 1 Camil 5kg',
        quantidade: 2,
        valorUnitario: 29.9,
        subtotal: 59.8,
      },
      {
        id: 'iv_02',
        produtoId: 'prod_002',
        codigoInterno: '102',
        nomeProduto: 'Feijão Carioca Kicaldo 1kg',
        quantidade: 2,
        valorUnitario: 8.9,
        subtotal: 17.8,
      },
    ],
    valorTotal: 77.6,
    desconto: 0,
    valorFinal: 77.6,
    formaPagamento: 'PIX',
    status: 'CONCLUIDA',
  },
  {
    id: 'venda_antiga_002',
    numeroCupom: 1002,
    dataHora: new Date(Date.now() - 3600 * 1000 * 2).toISOString(),
    operadorId: 'usr_caixa_01',
    operadorNome: 'Mariana Silva',
    itens: [
      {
        id: 'iv_03',
        produtoId: 'prod_008',
        codigoInterno: '108',
        nomeProduto: 'Refrigerante Coca-Cola 2L',
        quantidade: 1,
        valorUnitario: 10.5,
        subtotal: 10.5,
      },
      {
        id: 'iv_04',
        produtoId: 'prod_004',
        codigoInterno: '104',
        nomeProduto: 'Café Torrado Pilão Tradicional 500g',
        quantidade: 1,
        valorUnitario: 18.9,
        subtotal: 18.9,
      },
    ],
    valorTotal: 29.4,
    desconto: 0,
    valorFinal: 29.4,
    formaPagamento: 'DINHEIRO',
    valorRecebido: 30.0,
    troco: 0.6,
    status: 'CONCLUIDA',
  },
];
